#!/usr/bin/php
<?php

error_reporting(E_ALL|E_STRICT);
require __DIR__.'/PhrebarDeploymentManager.php';

$reinitializing = false;

$nonFlagArgs = [];
for( $i=1; $i<count($argv); ++$i ) {
	$arg = $argv[$i];
	switch( $arg ) {
	case '-f':
		$reinitializing = true;
		break;
	default:
		if( $arg[0] != '-' ) {
			$nonFlagArgs[] = $arg;
		} else {
			fwrite(STDERR, "Unrecognized argument: {$argv[$i]}\n");
			exit(1);
		}
	}
}

if( count($nonFlagArgs) < 3 ) {
   fwrite(STDERR, "Usage: create-deployment <name> <source repo> <commit>\n");
   exit(1);
}

$deploymentName = $nonFlagArgs[0];
$sourceRepo     = $nonFlagArgs[1];
$sourceCommit   = $nonFlagArgs[2];

$DM = new EarthIT_PhrebarDeploymentManager(__DIR__);
try {
	$DM->validate();
} catch( EarthIT_PhrebarDeploymentManager_EnvironmentException $e ) {
	fwrite(STDERR, $e->getMessage()."\n");
	exit(1);
}

$deployment = $DM->fillDeploymentInfo([
	'name'          => $deploymentName,
	'source-repo'   => $sourceRepo,
	'source-commit' => $sourceCommit
]);

try {
	if( file_exists($deployment['directory']) and !$reinitializing ) {
		throw new Exception("Deployment {$deploymentName} already exists.\n");
	}
	
	$DM->createDeployment($deployment);
} catch( Exception $e ) {
	fwrite(STDERR, "create-deployment: error: ".$e->getMessage()."\n");
	exit(1);
}
