#!/usr/bin/php
<?php

class EarthIT_PhrebarDeploymentServer {
	protected $DM;
	public function __construct( EarthIT_PhrebarDeploymentManager $DM ) {
		$this->DM = $DM;
	}
	
	public function doCommand( $cmd ) {
		if( is_string($cmd) ) {
			$cmd = trim($cmd);
			if( $cmd === '' or $cmd[0] === '#' ) return;
			$cmd = explode(' ',$cmd);
		}
		if( !is_array($cmd) ) throw new Exception("\$cmd must be a string or an array");
		if( count($cmd) === 0 ) return;
		
		switch( $cmd[0] ) {
		case 'sleep':
			if( isset($cmd[1]) ) {
				// Sleep that many seconds
				echo "# sleeping for {#cmd[1]} seconds\n";
				sleep($cmd[1]);
			} else {
				// Sleep forever!
				echo "# going to sleep forever (no more commands will be read)\n";
				while( true ) sleep(3600);
			}
			break;
		case 'create-deployment':
			if( count($cmd) < 4 ) {
				throw new Exception("'create-deployment' requires 3 arguments (deployment name, repo, commit)");
			}
			$deployment = $this->DM->fillDeploymentInfo([
				'name' => $cmd[1],
				'source-repo' => $cmd[2],
				'source-commit' => $cmd[3]
			]);
			$this->DM->createDeployment($deployment);
			echo "# created {$cmd[1]}; available at {$deployment['hostname']}\n";
			break;
		case 'destroy-deployment':
			if( count($cmd) < 2 ) {
				throw new Exception("'destroy-deployment' requires an argument (deployment name)");
			}
			$this->DM->destroyDeployment([
				'name' => $cmd[1]
			]);
			echo "# destroyed {$cmd[1]}\n";
			break;
		default:
			throw new Exception("Unrecognized command '{$cmd[0]}'");
		}
	}
}

error_reporting(E_ALL|E_STRICT);
require __DIR__.'/PhrebarDeploymentManager.php';

$configOverrides = [];
$commands = [];
$command = [];
for( $i=1; $i<count($argv); ++$i ) {
	$arg = $argv[$i];
	switch( $arg ) {
	case '-c':
		$kv = $argv[++$i];
		list($k,$v) = explode('=',$kv);
		$configOverrides[$k] = $v;
		break;
	default:
		if( $arg[0] === '+' ) {
			if( $command ) $commands[] = $command;
			$command = [substr($arg,1)];
		} else if( $arg[0] !== '-' and $command ) {
			$command[] = $arg;
		} else {
			fwrite(STDERR, "Unrecognized argument: {$arg}\n");
			exit(1);
		}
	}
}
if( $command ) {
	$commands[] = $command;
}
unset($command);

$DM = new EarthIT_PhrebarDeploymentManager(__DIR__);
foreach( $configOverrides as $k=>$v ) {
	$DM->setConfig($k, $v);
}
try {
	$DM->validate();
} catch( EarthIT_PhrebarDeploymentManager_EnvironmentException $e ) {
	fwrite(STDERR, $e->getMessage()."\n");
	exit(1);
}

$DS = new EarthIT_PhrebarDeploymentServer($DM);
$hadErrors = false;

echo "# deployment-server: Welcome!\n";

foreach( $commands as $cmd ) {
	$DS->doCommand($cmd);
}

while( ($line = fgets(STDIN,1024)) !== false ) {
	$line = trim($line);
	try {
		$DS->doCommand($line);
	} catch( Exception $e ) {
		echo "# error\n";
		fwrite(STDERR, "Error running command: $line:\n".$e->getMessage()."\n");
		$hadErrors = true;
	}
}

if( $hadErrors ) {
	exit(1);
} else {
	echo "# deployment-server: Quittin'\n";
}
