#!/usr/bin/php
<?php

error_reporting(E_ALL|E_STRICT);
require __DIR__.'/PhrebarDeploymentManager.php';

$deploymentNames = [];
for( $i=1; $i<count($argv); ++$i ) {
	$arg = $argv[$i];
	if( $arg[0] != '-' ) {
		$deploymentNames[] = $arg;
	} else switch( $arg ) {
		default:
			fwrite(STDERR, "Unrecognized argument: {$argv[$i]}\n");
			exit(1);
	}
}

$DM = new EarthIT_PhrebarDeploymentManager(__DIR__);
try {
	$DM->validateForDestroy();
} catch( EarthIT_PhrebarDeploymentManager_EnvironmentException $e ) {
	fwrite(STDERR, $e->getMessage()."\n");
	exit(1);
}

$errorCount = 0;
foreach( $deploymentNames as $deploymentName ) {
	try {
		$DM->destroyDeployment(['name'=>$deploymentName]);
	} catch( Exception $e ) {
		fwrite(STDERR, "destroy-deployment: error deleting {$deploymentName}: ".$e->getMessage()."\n");
		++$errorCount;
	}
}

exit( $errorCount ? 1 : 0 );
